### ISSUE TITLE
Unequal tracking results on different contexts

### ISSUE THREAD

**Issue by fsoubelet** [xsuite/xtrack#53] opened 2021-09-09 08:34 UTC
Hi, 

I was giving a go at the simple FODO example from the documentation, and tried the different contexts available to me.
However, it seems that doing the same tracking on two different contexts yields different results.

I am on a macbook pro machine (Intel CPU + Radeon Pro Vega 20 GPU), and tried the `CPU` and `OpenCL` contexts.
Here is a script which reproduces the issue for me:
```python
from typing import Union

import numpy as np

import xline as xl
import xobjects as xo
import xtrack as xt

SEQUENCE = xl.Line(
    elements=[
        xl.Drift(length=2.0),
        xl.Multipole(knl=[0, 1.0], ksl=[0, 0]),
        xl.Drift(length=1.0),
        xl.Multipole(knl=[0, -1.0], ksl=[0, 0]),
    ],
    element_names=["drift_0", "quad_0", "drift_1", "quad_1"],
)


def track_on_context(
    _context: Union[xo.ContextCpu, xo.ContextCupy, xo.ContextPyopencl],
    n_part: int = 200,
    n_turns: int = 10_000,
) -> np.ndarray:
    """
    Convenience function to track as the documentation's simple example on a given context, returning the
    resulting horizontal coordinates.

    Args:
        _context (Union[xo.ContextCpu, xo.ContextCupy, xo.ContextPyopencl]): `xobjects` context to build for.
        n_part (int): number of particles to track, defaults to 200.
        n_turns (int): number of turns to track for, defaults to 10000.

    Returns:
        Resulting X coordinates from tracking, as a `numpy.ndarray`.
    """
    # Transfer lattice on context and compile tracking code
    tracker = xt.Tracker(_context=_context, sequence=SEQUENCE)

    # Build particle object on context
    particles = xt.Particles(
        _context=_context,
        p0c=6500e9,
        x=np.random.uniform(-1e-3, 1e-3, n_part),
        px=np.random.uniform(-1e-5, 1e-5, n_part),
        y=np.random.uniform(-2e-3, 2e-3, n_part),
        py=np.random.uniform(-3e-5, 3e-5, n_part),
        zeta=np.random.uniform(-1e-2, 1e-2, n_part),
        delta=np.random.uniform(-1e-4, 1e-4, n_part),
    )

    # Track and return turn-by-turn
    tracker.track(particles, num_turns=n_turns, turn_by_turn_monitor=True)
    return tracker.record_last_track.x


# Track on CPU Context
context_cpu = xo.ContextCpu()
x_cpu = track_on_context(_context=context_cpu)

# Track on GPU Context
# macOS machine, using the OpenGL context as Metal is not supported
context_gpu = xo.ContextPyopencl()
x_gpu = track_on_context(_context=context_gpu)

# Comparing Tracking Data
print(np.array_equal(x_cpu, x_gpu))
```

The output in my case is, disregarding the compilation information, `False`.
Having a look at the arrays themselves, it is apparent they're very different.

I am available if you needs help debugging this on my machine.

**Comment by giadarol** [comment] 2021-09-09 10:39
Hi Felix, thanks for trying out Xsuite. The problem in in fact in your script, as you are regenerating the random particles each time you change context, so you are not comparing for the same initial conditions.

Here the corrected script, which passes the check on my machine:

```python
from typing import Union

import numpy as np

import xline as xl
import xobjects as xo
import xtrack as xt

SEQUENCE = xl.Line(
    elements=[
        xl.Drift(length=2.0),
        xl.Multipole(knl=[0, 1.0], ksl=[0, 0]),
        xl.Drift(length=1.0),
        xl.Multipole(knl=[0, -1.0], ksl=[0, 0]),
    ],
    element_names=["drift_0", "quad_0", "drift_1", "quad_1"],
)

n_part = 200
coord = {
    'p0c': 6500e9,
    'x': np.random.uniform(-1e-3, 1e-3, n_part),
    'px': np.random.uniform(-1e-5, 1e-5, n_part),
    'y': np.random.uniform(-2e-3, 2e-3, n_part),
    'py': np.random.uniform(-3e-5, 3e-5, n_part),
    'zeta': np.random.uniform(-1e-2, 1e-2, n_part),
    'delta': np.random.uniform(-1e-4, 1e-4, n_part),
}

def track_on_context(
    _context: Union[xo.ContextCpu, xo.ContextCupy, xo.ContextPyopencl],
    coord: dict,
    n_turns: int = 10_000,
) -> np.ndarray:
    """
    Convenience function to track as the documentation's simple example on a given context, returning the
    resulting horizontal coordinates.

    Args:
        _context (Union[xo.ContextCpu, xo.ContextCupy, xo.ContextPyopencl]): `xobjects` context to build for.
        n_part (int): number of particles to track, defaults to 200.
        n_turns (int): number of turns to track for, defaults to 10000.

    Returns:
        Resulting X coordinates from tracking, as a `numpy.ndarray`.
    """
    # Transfer lattice on context and compile tracking code
    tracker = xt.Tracker(_context=_context, sequence=SEQUENCE)

    # Build particle object on context
    particles = xt.Particles(
        _context=_context,
        **coord
    )

    # Track and return turn-by-turn
    tracker.track(particles, num_turns=n_turns, turn_by_turn_monitor=True)
    return tracker.record_last_track.x


# Track on CPU Context
context_cpu = xo.ContextCpu()
x_cpu = track_on_context(_context=context_cpu, coord=coord)

# Track on GPU Context
# macOS machine, using the OpenGL context as Metal is not supported
context_gpu = xo.ContextPyopencl()
x_gpu = track_on_context(_context=context_gpu, coord=coord)

# Comparing Tracking Data
print(np.array_equal(x_cpu, x_gpu))
```

**Comment by giadarol** [comment] 2021-09-09 10:43
BTW, things like this are checked in the Xtrack test suite. You can give it a go with pytest to check that Xsuite is behaving well with your GPU in a relatively wide series of cases.

**Comment by giadarol** [comment] 2021-09-09 10:44
Feel free to reopen the issue in case the problem is not solved by the change in the script

**Closed by giadarol** 2021-09-09 10:44 UTC

**Comment by fsoubelet** [comment] 2021-09-09 11:17
What a silly mistake, of course that fixed it on my side too.
Thanks Gianni :)

**Comment by giadarol** [comment] 2021-09-09 11:19
Cool!
